<?php

/**
 * @file
 * Test module for Promotion.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function commerce_promotion_test_form_views_form_commerce_cart_form_default_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We know that view forms are build on the base ID plus arguments.
  $order_id = substr($form_id, strlen('views_form_commerce_cart_form_default_'));

  // Use multiple coupon mode if the `test_multiple_coupons` parameter passed.
  $test_multiple_coupons = \Drupal::request()->query->has('test_multiple_coupons');

  $form['coupons'] = [
    '#type' => 'commerce_coupon_redemption_form',
    '#order_id' => $order_id,
    '#multiple_coupons' => $test_multiple_coupons,
  ];
}
