<?php

/**
 * @file
 * Provides activity logs for Commerce entities.
 */

use Drupal\commerce_log\PaymentListBuilder;

/**
 * Implements hook_preprocess_commerce_order().
 */
function commerce_log_preprocess_commerce_order(&$variables) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
  $order = $variables['elements']['#commerce_order'];
  $variables['order']['activity'] = [
    '#type' => 'view',
    '#name' => 'commerce_activity',
    '#display_id' => 'default',
    '#arguments' => [$order->id(), 'commerce_order'],
    '#embed' => TRUE,
    '#title' => t('Order activity'),
  ];
}

/**
 * Implements hook_entity_type_alter() for commerce_payment.
 */
function commerce_log_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['commerce_payment'])) {
    /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
    $entity_types['commerce_payment']->setListBuilderClass(PaymentListBuilder::class);
  }
}
