<?php

/**
 * @file
 * Provides activity logs for Commerce entities.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_preprocess_commerce_order().
 */
function commerce_log_preprocess_commerce_order(&$variables) {
  /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
  $order = $variables['elements']['#commerce_order'];
  $variables['order']['activity'] = [
    '#type' => 'view',
    '#name' => 'commerce_activity',
    '#display_id' => 'default',
    '#arguments' => [$order->id(), 'commerce_order'],
    '#embed' => TRUE,
    '#title' => t('Order activity'),
  ];
}

/**
 * Implements hook_entity_access().
 */
function commerce_log_entity_access(EntityInterface $entity, $operation, $account) {
  // Allow logs to be viewed by all users for now.
  // @todo Remove once we implement the full log permissions.
  if ($operation == 'view') {
    if ($entity->getEntityTypeId() == 'commerce_log') {
      return AccessResult::allowed();
    }
  }
  return AccessResult::neutral();
}
