<?php

/**
 * @file
 * Defines the Store entity type and common functions used by Commerce modules.
 */

use Drupal\commerce\Entity\CommerceStore;
use Drupal\commerce\Entity\CommerceStoreType;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function commerce_theme() {
  return array(
    'commerce_store_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'commerce.pages.inc',
      'template' => 'commerce-store-add-list',
    ),
  );
}

/**
 * Implements hook_toolbar().
 */
function commerce_toolbar() {
  $items = array();

  $items['commerce'] = array(
    '#type' => 'toolbar_item',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'commerce') . '/css/commerce.icons.css',
      ),
    ),
  );

  return $items;
}

/**
 * Returns the e-mail address from which to send commerce related e-mails.
 *
 * Currently this is just using the site's e-mail address, but this may be
 * updated to use a specific e-mail address when we add a settings form for the
 * store's physical address and contact information.
 */
function commerce_email_from() {
  return \Drupal::config('system.site')->get('mail');
}

/**
 * Implements hook_entity_operation().
 *
 * Add devel link if this entity type is /commerce_store[_type]/.
 */
function commerce_entity_operation(EntityInterface $entity) {
  $operations = array();
  if (!\Drupal::moduleHandler()->moduleExists('devel')) {
    return $operations;
  }

  $entity_routes = array(
    'commerce_store' => 'entity.commerce_store.devel',
    'commerce_store_type' => 'entity.commerce_store_type.devel',
  );

  $entity_type_id = $entity->getEntityTypeId();
  if (\Drupal::currentUser()->hasPermission('access devel information') && in_array($entity_type_id, array_keys($entity_routes))) {
    $operations['devel'] = array(
      'route_name' => $entity_routes[$entity_type_id],
      'route_parameters' => array($entity_type_id => $entity->id()),
      'title' => t('Devel'),
      'weight' => 15,
    );
  }

  return $operations;
}

/**
 * Returns the currency code of the site's default currency.
 */
function commerce_default_currency() {
  return \Drupal::config('commerce')->get('default_currency');
}
