<?php

/**
 * @file
 * Contains install and update functions for Checkout.
 */

use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_install().
 */
function commerce_checkout_install() {
  // Allow all roles to use checkout.
  user_role_grant_permissions(AccountInterface::ANONYMOUS_ROLE, ['access checkout']);
  user_role_grant_permissions(AccountInterface::AUTHENTICATED_ROLE, ['access checkout']);
}
