<?php
// $Id$

/**
 * @file
 * Defines a field type for referencing products from other entities.
 */

/**
 * Implements hook_field_info().
 */
function commerce_product_reference_field_info() {
  return array(
    'commerce_product_reference' => array(
      'label' => t('Product reference'),
      'description' => t('This field stores the ID of a related product as an integer value.'),
      'default_widget' => 'options_select',
      'default_formatter' => 'commerce_product_reference_title_link',
      'settings' => array(
        'referenceable_types' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_field_schema().
 */
function commerce_product_reference_field_schema($field) {
  return array(
    'columns' => array(
      'product_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'product_id' => array('product_id'),
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function commerce_product_reference_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  $options = array();
  $form = array();

  // Build an options array of the product types.
  foreach (commerce_product_types() as $type) {
    $options[$type['product_type']] = check_plain($type['name']);
  }

  $form['referenceable_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Product types that can be referenced'),
    '#description' => t('If no types are selected, any type of product may be referenced.'),
    '#options' => $options,
    '#default_value' => is_array($settings['referenceable_types']) ? $settings['referenceable_types'] : array(),
    '#multiple' => TRUE,
    '#disabled' => $has_data,
  );

  return $form;
}

/**
 * Implements hook_field_validate().
 *
 * Possible error codes:
 * - 'invalid_product_id': product_id is not valid for the field (not a valid
 *                         product id, or the product is not referenceable).
 */
function commerce_product_reference_field_validate($obj_type, $object, $field, $instance, $langcode, $items, &$errors) {
  // Extract product_ids to check.
  $ids = array();

  // First check non-numeric product_id's to avoid losing time with them.
  foreach ($items as $delta => $item) {
    if (is_array($item) && !empty($item['product_id'])) {
      if (is_numeric($item['product_id'])) {
        $ids[] = $item['product_id'];
      }
      else {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'invalid_product_id',
          'message' => t("%name: invalid input.", array('%name' => $instance['label'])),
        );
      }
    }
  }

  // Prevent performance hog if there are no ids to check.
  if ($ids) {
    $refs = commerce_product_match_products($field, '', NULL, $ids);

    foreach ($items as $delta => $item) {
      if (is_array($item)) {
        if (!empty($item['product_id']) && !isset($refs[$item['product_id']])) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'invalid_product_id',
            'message' => t("%name: this product can't be referenced.", array('%name' => $instance['label'])),
          );
        }
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function commerce_product_reference_field_is_empty($item, $field) {
  // product_id = 0 îs empty too, which is exactly what we want.
  return empty($item['product_id']);
}

/**
 * Implements hook_field_formatter_info().
 */
function commerce_product_reference_field_formatter_info() {
  return array(
    'commerce_product_reference_sku_link' => array(
      'label' => t('SKU (link)'),
      'description' => t('Display the SKU of the referenced product as a link to the node page.'),
      'field types' => array('commerce_product_reference'),
    ),
    'commerce_product_reference_sku_plain' => array(
      'label' => t('SKU (no link)'),
      'description' => t('Display the SKU of the referenced product as plain text.'),
      'field types' => array('commerce_product_reference'),
    ),
    'commerce_product_reference_title_link' => array(
      'label' => t('Title (link)'),
      'description' => t('Display the title of the referenced product as a link to the node page.'),
      'field types' => array('commerce_product_reference'),
    ),
    'commerce_product_reference_title_plain' => array(
      'label' => t('Title (no link)'),
      'description' => t('Display the title of the referenced product as plain text.'),
      'field types' => array('commerce_product_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function commerce_product_reference_field_formatter_view($obj_type, $object, $field, $instance, $langcode, $items, $display) {
  $result = array();

  // @todo Optimisation: use hook_field_formatter_prepare_view() to load
  // node titles or full nodes in 'multiple' mode.

  // Collect the list of node ids.
  $product_ids = array();

  foreach ($items as $delta => $item) {
    $product_ids[$item['product_id']] = $item['product_id'];
  }

  $products = _commerce_product_reference_get_product_data($product_ids);

  switch ($display['type']) {
    case 'commerce_product_reference_sku_link':
    case 'commerce_product_reference_sku_plain':
      foreach ($items as $delta => $item) {
        if ($display['type'] == 'commerce_product_reference_sku_link') {
          $result[$delta] = array(
            '#type' => 'link',
            '#title' => $products[$item['product_id']]['sku'],
            '#href' => 'admin/commerce/products/' . $item['product_id'],
          );
        }
        else {
          $result[$delta] = array(
            '#markup' => check_plain($products[$item['product_id']]['sku']),
          );
        }
      }
      break;

    case 'commerce_product_reference_title_link':
    case 'commerce_product_reference_title_plain':
      foreach ($items as $delta => $item) {
        if ($display['type'] == 'commerce_product_reference_title_link') {
          $result[$delta] = array(
            '#type' => 'link',
            '#title' => $products[$item['product_id']]['title'],
            '#href' => 'admin/commerce/products/' . $item['product_id'],
          );
        }
        else {
          $result[$delta] = array(
            '#markup' => check_plain($products[$item['product_id']]['title']),
          );
        }
      }
      break;
  }

  return $result;
}

/**
 * Loads and caches product SKUs and titles for the current request.
 *
 * @param $product_ids
 *   An array of product IDs to load.
 * @param $known_products
 *   An array of product data to cache at this time. Should be in the format of
 *     an array keyed by product_id with the value being an array with the keys
 *     'sku' and 'title'.
 * @return
 *   An array of product data keyed by product_id with the value being an array
 *     with the keys 'sku' and 'title'.
 */
function _commerce_product_reference_get_product_data($product_ids, $known_products = array()) {
  $products = &drupal_static(__FUNCTION__, array());

  // Save titles we receive.
  $products += $known_products;

  // Collect product_ids to retrieve from database.
  $product_ids_query = array();

  foreach ($product_ids as $product_id) {
    if (!isset($products[$product_id])) {
      $product_ids_query[] = $product_id;
    }
  }

  // If there are unknown product IDs...
  if ($product_ids_query) {
    // Load the specified products.
    $query = db_select('commerce_product', 'cp')
      ->fields('cp', array('product_id', 'sku', 'title'))
      ->condition('cp.product_id', $product_ids);

    $data = $query->execute()->fetchAll();

    foreach ($data as $product) {
      $products[$product->product_id] = array(
        'sku' => $product->sku,
        'title' => $product->title,
      );
    }
  }

  // Build the results array.
  $return = array();

  foreach ($product_ids as $product_id) {
    $return[$product_id] = array(
      'sku' => isset($products[$product_id]['sku']) ? $products[$product_id]['sku'] : '',
      'title' => isset($products[$product_id]['title']) ? $products[$product_id]['title'] : '',
    );
  }

  return $return;
}


/**
 * Implements hook_field_widget_info().
 *
 * Defines widgets available for use with field types as specified in each
 * widget's $info['field types'] array.
 */
function commerce_product_reference_field_widget_info() {
  $widgets = array();

  // Define an autocomplete textfield widget for product referencing that works
  // like the Term Reference autocomplete widget.
  $widgets['commerce_product_reference_autocomplete'] = array(
    'label' => t('Autocomplete text field'),
    'description' => t('Display the list of referenceable products as a textfield with autocomplete behaviour.'),
    'field types' => array('commerce_product_reference'),
    'settings' => array(
      'autocomplete_match' => 'contains',
      'size' => 60,
      'autocomplete_path' => 'commerce_product/autocomplete',
    ),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_info_alter().
 */
function commerce_product_reference_field_widget_info_alter(&$info) {
  $info['options_select']['field types'][] = 'commerce_product_reference';
  $info['options_buttons']['field types'][] = 'commerce_product_reference';
}

/**
 * Implements hook_field_widget_settings_form().
 */
function commerce_product_reference_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $defaults = field_info_widget_settings($widget['type']);
  $settings = array_merge($defaults, $widget['settings']);

  $form = array();

  // Build the settings for the product reference autocomplete widget.
  if ($widget['type'] == 'commerce_product_reference_autocomplete') {
    $form['autocomplete_match'] = array(
      '#type' => 'select',
      '#title' => t('Autocomplete matching'),
      '#default_value' => $settings['autocomplete_match'],
      '#options' => array(
        'starts_with' => t('Starts with'),
        'contains' => t('Contains'),
      ),
      '#description' => t('Select the method used to collect autocomplete suggestions. Note that <em>Contains</em> can cause performance issues on sites with thousands of nodes.'),
    );
    $form['size'] = array(
      '#type' => 'textfield',
      '#title' => t('Size of textfield'),
      '#default_value' => $settings['size'],
      '#element_validate' => array('_element_validate_integer_positive'),
      '#required' => TRUE,
    );
  }

  return $form;
}

/**
 * Implements hook_field_widget_form().
 *
 * Used to define the form element for custom widgets.
 */
function commerce_product_reference_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  // Define the autocomplete textfield for products.
  if ($instance['widget']['type'] == 'commerce_product_reference_autocomplete') {
    $product_ids = array();
    $skus = array();

    // Build an array of product IDs from this field's values.
    foreach ($items as $item) {
      $product_ids[] = $item['product_id'];
    }

    // Load those products and loop through them to extract their SKUs.
    $products = commerce_product_load_multiple($product_ids);

    foreach ($product_ids as $product_id) {
      $skus[] = $products[$product_id]->sku;
    }

    return $element + array(
        '#type' => 'textfield',
        '#default_value' => implode(', ', $skus),
        '#autocomplete_path' => $instance['widget']['settings']['autocomplete_path'] . '/' . $field['field_name'],
        '#size' => $instance['widget']['settings']['size'],
        '#element_validate' => array('commerce_product_reference_autocomplete_validate'),
    );
  }
}

/**
 * Validation callback for a commerce_product_reference autocomplete element.
 *
 * TODO: Validate by product type if specified.
 */
function commerce_product_reference_autocomplete_validate($element, &$form_state, $form) {
  $field = $form['#fields'][$element['#field_name']]['field'];
  $instance = $form['#fields'][$element['#field_name']]['instance'];

  if (!empty($element['#value'])) {
    // Translate SKUs into product IDs.
    $typed_skus = drupal_explode_tags($element['#value']);

    $value = array();

    foreach ($typed_skus as $typed_sku) {
      // See if the SKU exists in the valid product types and return the tid.
      if ($products = commerce_product_load_multiple(array(), array('sku' => trim($typed_sku)))) {
        $product = array_pop($products);
        $value[] = array('product_id' => $product->product_id);
      }
    }
  }
  else {
    $value = array();
  }

  form_set_value($element, $value, $form_state);
}

/**
 * Implements hook_field_widget_error().
 */
function commerce_product_reference_field_widget_error($element, $error) {
  form_error($element, $error['message']);
}

/**
 * Implements hook_commerce_product_type_update().
 *
 * Reflect type name changes to the 'referenceable types' settings: when the
 * name of a type changes, the change needs to be reflected in the
 * "referenceable types" setting for any commerce_product_reference field
 * referencing it.
 *
 * TODO: Implement this hook.
 */
function commerce_product_reference_commerce_product_type_update($info) {
  if (!empty($info->old_type) && $info->old_type != $info->type) {
    $fields = field_info_fields();

    foreach ($fields as $field_name => $field) {
      if ($field['type'] == 'commerce_product_reference' && isset($field['settings']['referenceable_types'][$info->old_type])) {
        $field['settings']['referenceable_types'][$info->type] = empty($field['settings']['referenceable_types'][$info->old_type]) ? 0 : $info->type;
        unset($field['settings']['referenceable_types'][$info->old_type]);
        field_update_field($field);
      }
    }
  }
}

/**
 * Implements hook_field_prepare_translation().
 *
 * When preparing a translation, load any translations of existing references.
 * @todo Core doc: "This hook may or may not survive in Field API".
 * So it is currently not verified.
 *
function node_reference_field_prepare_translation($obj_type, $object, $field, $instance, $langcode, &$items) {
  $addition = array();
  $addition[$field['field_name']] = array();
  if (isset($object->translation_source->$field['field_name'])
  && is_array($object->translation_source->$field['field_name'])) {
    foreach ($object->translation_source->$field['field_name'] as $key => $reference) {
      $reference_node = node_load($reference['nid']);
      // Test if the referenced node type is translatable and, if so,
      // load translations if the reference is not for the current language.
      // We can assume the translation module is present because it invokes 'prepare translation'.
      if (translation_supported_type($reference_node->type)
      && !empty($reference_node->language)
      && $reference_node->language != $node->language
      && $translations = translation_node_get_translations($reference_node->tnid)) {
        // If there is a translation for the current language, use it.
        $addition[$field['field_name']][] = array(
          'nid' => isset($translations[$node->language])
            ? $translations[$node->language]->nid
            : $reference['nid'],
        );
      }
    }
  }

  return $addition;
}
 */

/**
 * Implements hook_options_list().
 */
function commerce_product_reference_options_list($field) {
  $options = array();

  // Loop through all product matches.
  foreach (commerce_product_match_products($field) as $product_id => $data) {
    // Add them to the options list in optgroups by product type.
    $name = check_plain(commerce_product_type_get_name($data['product_type']));
    $options[$name][$product_id] = t('@sku: @title', array('@sku' => $data['sku'], '@title' => $data['title']));
  }

  // Simplify the options list if only one optgroup exists.
  if (count(array_keys($options)) == 1) {
    $options = $options[array_shift(array_keys($options))];
  }

  return $options;
}
