<?php
// $Id$

/**
 * @file
 * Provides a NULL payment method for Drupal Commerce.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_payment_null_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_payment_null'] = (object) array(
    'title' => t('No payment'),
    'description' => t('No payment necessary.'),
  );

  return $payment_methods;
}

/**
 * Settings callback for the payment method.
 */
function commerce_payment_null_settings($settings = NULL) {
  $form = array();

  $form['test'] = array(
    '#type' => 'textfield',
    '#title' => t('Test of field'),
    '#default_value' => isset($settings['test']) ? $settings['test'] : '',
  );

  return $form;
}

/**
 * Checkout form callback for the payment method.
 */
function commerce_payment_null_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form = array();

  // Merge in values from the order.
  if (isset($order->data['commerce_payment_null'])) {
    $pane_values += $order->data['commerce_payment_null'];
  }

  // Merge in default values.
  $pane_values += array(
    'name' => '',
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => $pane_values['name'],
  );

  return $form;
}

/**
 * Submission form callback for the payment method.
 */
function commerce_payment_null_submit_form_submit($payment_method, $pane_form, $pane_values, $order) {
  $order->data['commerce_payment_null'] = $pane_values;
}
