<?php

namespace Drupal\commerce_product\Entity;

use Drupal\Core\Config\Entity\ConfigEntityInterface;

/**
 * Defines the interface for product variation types.
 */
interface ProductVariationTypeInterface extends ConfigEntityInterface {

  /**
   * Gets the product variation type's line item type.
   *
   * Used for finding/creating the appropriate line item when purchasing a
   * product (adding it to an order).
   *
   * @return string
   *   The line item type.
   */
  public function getLineItemType();

  /**
   * Sets the product variation type's line item type.
   *
   * @param string $line_item_type
   *   The line item type.
   *
   * @return $this
   */
  public function setLineItemType($line_item_type);

  /**
   * Set the product variation type's title autogeneration.
   *
   * @param bool $autogenerate
   *   Whether to autogenerate the title or not.
   *
   * @return $this
   */
  public function setTitleAutogenerated($autogenerate);

  /**
   * Whether the product variation type supports title autogeneration.
   *
   * @return bool
   *   Whether to autogenerate the title or not.
   */
  public function isTitleAutogenerated();

}
