<?php
// $Id$

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_product_ui_menu() {
  $items = array();

  // Note: admin/commerce/products will be created by Views.

  // Add a product.
  $items['admin/commerce/products/add'] = array(
    'title' => 'Add a product',
    'description' => 'Add a new product for sale.',
    'page callback' => 'commerce_product_ui_add_page',
    'access callback' => 'commerce_product_ui_product_add_any_access',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.products.inc',
  );
  foreach (commerce_product_types() as $type => $product_type) {
    $items['admin/commerce/products/add/' . $type] = array(
      'title' => 'Create @name',
      'title arguments' => array('@name' => $product_type->name),
      'description' => $product_type->description,
      'page callback' => 'commerce_product_ui_product_form',
      'page arguments' => array(commerce_product_new($type)),
      'access callback' => 'commerce_product_access',
      'access arguments' => array('create', $type),
      'file' => 'includes/commerce_product_ui.products.inc',
    );
  }

  $items['admin/commerce/products/%commerce_product'] = array(
    'title callback' => 'commerce_product_ui_product_title',
    'title arguments' => array(3),
    'page callback' => 'commerce_product_ui_product_form',
    'page arguments' => array(3),
    'access callback' => 'commerce_product_access',
    'access arguments' => array('update', 3),
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_product_ui.products.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/commerce/products/%commerce_product/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/products/%commerce_product/delete'] = array(
    'title' => 'Delete a product',
    'page callback' => 'commerce_product_ui_product_delete_form',
    'page arguments' => array(3),
    'access callback' => 'commerce_product_access',
    'access arguments' => array('update', 3),
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_product_ui.products.inc',
  );

  $items['admin/commerce/products/types'] = array(
    'title' => 'Product types',
    'description' => 'Manage products types for your store.',
    'page callback' => 'commerce_product_ui_types_overview',
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/add'] = array(
    'title' => 'Add product type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_product_ui_type_form', commerce_product_type_new()),
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_ACTION | MENU_VISIBLE_IN_BREADCRUMB,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/%commerce_product_type'] = array(
    'title callback' => 'commerce_product_type_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_product_ui_type_form', 4),
    'access arguments' => array('administer product types'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/%commerce_product_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/products/types/%commerce_product_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_product_ui_type_delete_form', 4),
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.types.inc',
  );

  return $items;
}

/**
 * Menu item title callback: returns the SKU of a product for its pages.
 *
 * @param $product
 *   The product object as loaded via the URL wildcard.
 * @return
 *   A page title of the format "Product: [SKU]".
 */
function commerce_product_ui_product_title($product) {
  return t('Product: @sku', array('@sku' => $product->sku));
}

/**
 * Access callback: determine if the user can create any type of product.
 */
function commerce_product_ui_product_add_any_access() {
  // Grant automatic access to users with administer products permission.
  if (user_access('administer products')) {
    return TRUE;
  }

  // Check the user's access on a product type basis.
  foreach (commerce_product_types() as $type => $product_type) {
    if (commerce_product_ui_product_add_access($type)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_menu_alter().
 */
function commerce_product_ui_menu_alter(&$items) {
  // Transform the field UI tabs into contextual links.
  $items['admin/commerce/products/types/%commerce_product_type/fields']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
  $items['admin/commerce/products/types/%commerce_product_type/display']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}

/**
 * Implements hook_admin_paths().
 */
function commerce_product_ui_admin_paths() {
  $paths = array(
    'admin/commerce/products' => TRUE,
    'admin/commerce/products/list' => TRUE,
    'admin/commerce/products/add' => TRUE,
    'admin/commerce/products/add/*' => TRUE,
    'admin/commerce/products/*' => TRUE,
    'admin/commerce/products/*/view' => TRUE,
    'admin/commerce/products/*/edit' => TRUE,
    'admin/commerce/products/*/delete' => TRUE,
    'admin/commerce/products/types' => TRUE,
    'admin/commerce/products/types/add' => TRUE,
    'admin/commerce/products/types/*' => TRUE,
    'admin/commerce/products/types/*/edit' => TRUE,
    'admin/commerce/products/types/*/delete' => TRUE,
    'admin/commerce/products/types/*/fields' => TRUE,
    'admin/commerce/products/types/*/display' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_help().
 */
function commerce_product_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/commerce/products/types/add':
      return '<p>' . t('Individual product types can have different fields assigned to them.') . '</p>';
  }

  // Return the user defined help text per product type when adding products.
  if ($arg[1] == 'commerce' && $arg[2] == 'products' && $arg[3] == 'add' && $arg[4]) {
    $product_type = commerce_product_type_load(str_replace('-', '_', $arg[4]));
    return (!empty($product_type->help) ? '<p>' . filter_xss_admin($product_type->help) . '</p>' : '');
  }
}

/**
 * Implements hook_theme().
 */
function commerce_product_ui_theme() {
  return array(
    'product_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'includes/commerce_product_ui.products.inc',
    ),
    'product_type_admin_overview' => array(
      'variables' => array('type' => NULL),
      'file' => 'includes/commerce_product_ui.types.inc',
    ),
    'commerce_product_sku' => array(
      'variables' => array('sku' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-sku',
    ),
    'commerce_product_title' => array(
      'variables' => array('title' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-title',
    ),
    'commerce_product_status' => array(
      'variables' => array('status' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-status',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 *
 * Exposes the admin UI for product fields.
 */
function commerce_product_ui_entity_info_alter(&$entity_info) {
  foreach ($entity_info['commerce_product']['bundles'] as $type => &$bundle) {
    $bundle['admin'] = array(
      'path' => 'admin/commerce/products/types/%commerce_product_type',
      'real path' => 'admin/commerce/products/types/' . $type,
      'bundle argument' => 4,
      'access arguments' => array('administer product types'),
    );
  }
}

/**
 * Implements hook_field_ui_view_modes_tabs().
 */
function commerce_product_ui_field_ui_view_modes_tabs($entity_type) {
  if ($entity_type == 'commerce_product') {
    $modes = array(
      'basic' => array(
        'view modes' => array('full'),
      ),
      'node' => array(
        'title' => t('Node'),
        'view modes' => array('node_teaser', 'node_full', 'node_rss'),
      ),
    );

    return $modes;
  }
}

/**
 * Implements hook_views_api().
 */
function commerce_product_ui_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'commerce_product_ui') . '/includes/views',
  );
}

/**
 * Sets the breadcrumb for administrative product pages.
 */
function commerce_product_ui_set_breadcrumb() {
  $breadcrumb = array(
    l(t('Home'), '<front>'),
    l(t('Dashboard'), 'admin'),
    l(t('Store'), 'admin/commerce'),
    l(t('Products'), 'admin/commerce/products'),
  );

  drupal_set_breadcrumb($breadcrumb);
}
