<?php
// $Id$

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_product_ui_menu() {
  $items = array();

  // Note: admin/commerce/products is defined by a default View.

  // Add a product.
  $items['admin/commerce/products/add'] = array(
    'title' => 'Add a product',
    'description' => 'Add a new product for sale.',
    'page callback' => 'commerce_product_ui_add_page',
    'access callback' => 'commerce_product_ui_product_add_any_access',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.products.inc',
  );
  foreach (commerce_product_types() as $type => $product_type) {
    $items['admin/commerce/products/add/' . $type] = array(
      'title' => 'Create @name',
      'title arguments' => array('@name' => $product_type->name),
      'description' => $product_type->description,
      'page callback' => 'commerce_product_ui_product_form_wrapper',
      'page arguments' => array(commerce_product_new($type)),
      'access callback' => 'commerce_product_access',
      'access arguments' => array('create', $type),
      'file' => 'includes/commerce_product_ui.products.inc',
    );
  }

  $items['admin/commerce/products/%commerce_product'] = array(
    'title callback' => 'commerce_product_ui_product_title',
    'title arguments' => array(3),
    'page callback' => 'commerce_product_ui_product_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_product_access',
    'access arguments' => array('update', 3),
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_product_ui.products.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/commerce/products/%commerce_product/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/products/%commerce_product/delete'] = array(
    'title' => 'Delete a product',
    'page callback' => 'commerce_product_ui_product_delete_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_product_access',
    'access arguments' => array('update', 3),
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_product_ui.products.inc',
  );

  $items['admin/commerce/products/types'] = array(
    'title' => 'Product types',
    'description' => 'Manage products types for your store.',
    'page callback' => 'commerce_product_ui_types_overview',
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/add'] = array(
    'title' => 'Add product type',
    'page callback' => 'commerce_product_ui_product_type_form_wrapper',
    'page arguments' => array(commerce_product_type_new()),
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_ACTION | MENU_VISIBLE_IN_BREADCRUMB,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/%commerce_product_type'] = array(
    'title callback' => 'commerce_product_type_title',
    'title arguments' => array(4),
    'page callback' => 'commerce_product_ui_product_type_form_wrapper',
    'page arguments' => array(4),
    'access arguments' => array('administer product types'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_product_ui.types.inc',
  );
  $items['admin/commerce/products/types/%commerce_product_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/products/types/%commerce_product_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'commerce_product_ui_product_type_delete_form_wrapper',
    'page arguments' => array(4),
    'access arguments' => array('administer product types'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 10,
    'file' => 'includes/commerce_product_ui.types.inc',
  );

  return $items;
}

/**
 * Menu item title callback: returns the SKU of a product for its pages.
 *
 * @param $product
 *   The product object as loaded via the URL wildcard.
 * @return
 *   A page title of the format "Product: [SKU]".
 */
function commerce_product_ui_product_title($product) {
  return t('Product: @sku', array('@sku' => $product->sku));
}

/**
 * Access callback: determine if the user can create any type of product.
 */
function commerce_product_ui_product_add_any_access() {
  // Grant automatic access to users with administer products permission.
  if (user_access('administer products')) {
    return TRUE;
  }

  // Check the user's access on a product type basis.
  foreach (commerce_product_types() as $type => $product_type) {
    if (commerce_product_ui_product_add_access($type)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_menu_alter().
 */
function commerce_product_ui_menu_alter(&$items) {
  // Transform the field UI tabs into contextual links.
  $items['admin/commerce/products/types/%commerce_product_type/fields']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
  $items['admin/commerce/products/types/%commerce_product_type/display']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
}

/**
 * Implements hook_help().
 */
function commerce_product_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/commerce/products/types/add':
      return '<p>' . t('Individual product types can have different fields assigned to them.') . '</p>';
  }

  // Return the user defined help text per product type when adding products.
  if ($arg[1] == 'commerce' && $arg[2] == 'products' && $arg[3] == 'add' && $arg[4]) {
    $product_type = commerce_product_type_load(str_replace('-', '_', $arg[4]));
    return (!empty($product_type->help) ? '<p>' . filter_xss_admin($product_type->help) . '</p>' : '');
  }
}

/**
 * Implements hook_theme().
 */
function commerce_product_ui_theme() {
  return array(
    'product_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'includes/commerce_product_ui.products.inc',
    ),
    'product_type_admin_overview' => array(
      'variables' => array('type' => NULL),
      'file' => 'includes/commerce_product_ui.types.inc',
    ),
    'commerce_product_sku' => array(
      'variables' => array('sku' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-sku',
    ),
    'commerce_product_title' => array(
      'variables' => array('title' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-title',
    ),
    'commerce_product_status' => array(
      'variables' => array('status' => NULL, 'label' => NULL, 'product' => NULL),
      'path' => drupal_get_path('module', 'commerce_product_ui') . '/theme',
      'template' => 'commerce-product-status',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 *
 * Exposes the admin UI for product fields.
 */
function commerce_product_ui_entity_info_alter(&$entity_info) {
  foreach ($entity_info['commerce_product']['bundles'] as $type => &$bundle) {
    $bundle['admin'] = array(
      'path' => 'admin/commerce/products/types/%commerce_product_type',
      'real path' => 'admin/commerce/products/types/' . $type,
      'bundle argument' => 4,
      'access arguments' => array('administer product types'),
    );
  }
}

/**
 * Implements hook_field_ui_view_modes_tabs().
 */
function commerce_product_ui_field_ui_view_modes_tabs($entity_type) {
  if ($entity_type == 'commerce_product') {
    $modes = array(
      'basic' => array(
        'view modes' => array('full'),
      ),
      'node' => array(
        'title' => t('Node'),
        'view modes' => array('node_teaser', 'node_full', 'node_rss'),
      ),
    );

    return $modes;
  }
}

/**
 * Implements hook_forms().
 */
function commerce_product_ui_forms($form_id, $args) {
  $forms = array();

  // Define a wrapper ID for the product type add / edit form.
  $forms['commerce_product_ui_product_type_form'] = array(
    'callback' => 'commerce_product_product_type_form',
  );

  // Define a wrapper ID for the product type delete confirmation form.
  $forms['commerce_product_ui_product_type_delete_form'] = array(
    'callback' => 'commerce_product_product_type_delete_form',
  );

  // Define a wrapper ID for the product add / edit form.
  $forms['commerce_product_ui_product_form'] = array(
    'callback' => 'commerce_product_product_form',
  );

  // Define a wrapper ID for the product delete confirmation form.
  $forms['commerce_product_ui_product_delete_form'] = array(
    'callback' => 'commerce_product_product_delete_form',
  );

  return $forms;
}

/**
 * Implements hook_form_alter().
 */
function commerce_product_ui_form_alter(&$form, &$form_state, $form_id) {
  // On field administration forms for product types add a breadcrumb.
  if (in_array($form_id, array('field_ui_field_overview_form', 'field_ui_display_overview_form'))) {
    if ($form['#entity_type'] == 'commerce_product') {
      commerce_product_ui_set_breadcrumb(TRUE);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Product UI module instantiates the product type add/edit form at
 * particular paths in the Commerce IA. It uses its own form ID to do so and
 * alters the form here to add in appropriate redirection and buttons.
 *
 * @see commerce_product_ui_product_type_form()
 */
function commerce_product_ui_form_commerce_product_ui_product_type_form_alter(&$form, &$form_state) {
  // Add a submit handler to the save button to add a redirect.
  $form['actions']['submit']['#submit'][] = 'commerce_product_ui_product_type_form_submit';

  if (!empty($form_state['product_type']->type)) {
    $form['actions']['delete'] = array(
      '#type' => 'submit',
      '#value' => t('Delete product type'),
      '#suffix' => l('Cancel', 'admin/commerce/products/types'),
      '#submit' => array('commerce_product_ui_product_type_form_delete_submit'),
      '#weight' => 45,
    );
  }
  else {
    $form['actions']['save_continue'] = array(
      '#type' => 'submit',
      '#value' => t('Save and add fields'),
      '#suffix' => l('Cancel', 'admin/commerce/products/types'),
      '#submit' => array('commerce_product_product_type_form_submit', 'commerce_product_ui_product_type_form_submit'),
      '#weight' => 45,
    );
  }
}

/**
 * Submit callback for delete button on commerce_product_ui_product_type_form().
 *
 * @see commerce_product_ui_form_commerce_product_ui_product_type_form_alter()
 */
function commerce_product_ui_product_type_form_delete_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/products/types/' . $form_state['product_type']->type .'/delete';
}

/**
 * Submit callback for commerce_product_ui_product_type_form().
 *
 * @see commerce_product_ui_form_commerce_product_ui_product_type_form_alter()
 */
function commerce_product_ui_product_type_form_submit($form, &$form_state) {
  if ($form_state['clicked_button']['#parents'][0] == 'save_continue') {
    $form_state['redirect'] = 'admin/commerce/products/types/' . $form_state['product_type']->type . '/fields';
  }
  else {
    $form_state['redirect'] = 'admin/commerce/products/types';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Product UI module instantiates the product type delete form at a
 * particular path in the Commerce IA. It uses its own form ID to do so and
 * alters the form here to add in appropriate redirection.
 *
 * @see commerce_product_ui_product_type_delete_form()
 */
function commerce_product_ui_form_commerce_product_ui_product_type_delete_form_alter(&$form, &$form_state) {
  $form['actions']['cancel']['#markup'] = l(t('Cancel'), 'admin/commerce/products/types');

  $form['#submit'][] = 'commerce_product_ui_product_type_delete_form_submit';
}

/**
 * Submit callback for commerce_product_ui_product_type_delete_form().
 *
 * @see commerce_product_ui_form_commerce_product_ui_product_type_delete_form_alter()
 */
function commerce_product_ui_product_type_delete_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/products/types';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Product UI module instantiates the Product add/edit form at particular
 * paths in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection and an additional button.
 *
 * @see commerce_product_ui_product_form()
 */
function commerce_product_ui_form_commerce_product_ui_product_form_alter(&$form, &$form_state) {
  // Add a submit handler to the save button to add a redirect.
  $form['actions']['submit']['#submit'][] = 'commerce_product_ui_product_form_submit';

  // Add the save and continue button for new products.
  if (empty($form_state['commerce_product']->product_id)) {
    $form['actions']['save_continue'] = array(
      '#type' => 'submit',
      '#value' => t('Save and add another'),
      '#submit' => $form['actions']['submit']['#submit'],
      '#suffix' => l('Cancel', 'admin/commerce/products'),
      '#weight' => 45,
    );
  }
  else {
    $form['actions']['submit']['#suffix'] = l('Cancel', 'admin/commerce/products');
  }
}

/**
 * Submit callback for commerce_product_ui_product_form().
 *
 * @see commerce_product_ui_form_commerce_product_ui_product_form_alter()
 */
function commerce_product_ui_product_form_submit($form, &$form_state) {
  // Set the redirect based on the button clicked.
  if ($form_state['clicked_button']['#parents'][0] == 'save_continue') {
    $form_state['redirect'] = 'admin/commerce/products/add/' . $form_state['commerce_product']->type;
  }
  elseif (arg(2) == 'products' && arg(3) == 'add') {
    $form_state['redirect'] = 'admin/commerce/products';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Product UI module instantiates the Product delete form at a particular
 * path in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection.
 *
 * @see commerce_product_ui_product_delete_form()
 */
function commerce_product_ui_form_commerce_product_ui_product_delete_form_alter(&$form, &$form_state) {
  $form['actions']['cancel']['#markup'] = l(t('Cancel'), 'admin/commerce/products');

  $form['#submit'][] = 'commerce_product_ui_product_delete_form_submit';
}

/**
 * Submit callback for commerce_product_ui_product_delete_form().
 *
 * @see commerce_product_ui_form_commerce_product_ui_product_delete_form_alter()
 */
function commerce_product_ui_product_delete_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/products';
}

/**
 * Implements hook_views_api().
 */
function commerce_product_ui_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'commerce_product_ui') . '/includes/views',
  );
}

/**
 * Sets the breadcrumb for administrative product pages.
 *
 * @param $product_types
 *   TRUE or FALSE indicating whether or not the breadcrumb should include the
 *     product types administrative page.
 */
function commerce_product_ui_set_breadcrumb($product_types = FALSE) {
  $breadcrumb = array(
    l(t('Home'), '<front>'),
    l(t('Dashboard'), 'admin'),
    l(t('Store'), 'admin/commerce'),
    l(t('Products'), 'admin/commerce/products'),
  );

  if ($product_types) {
    $breadcrumb[] = l(t('Product types'), 'admin/commerce/products/types');
  }

  drupal_set_breadcrumb($breadcrumb);
}
