<?php
use Drupal\commerce_log\Entity\Log;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function commerce_log_test_entity_test_create(EntityInterface $entity) {
  /** @var \Drupal\commerce_log\LogStorageInterface $log_storage */
  $log_storage = \Drupal::entityTypeManager()->getStorage('commerce_log');
  $params = [
    'entity_label' => $entity->label(),
  ];
  $log = $log_storage->generate($entity, 'entity_test_created', $params);
  $log->save();
}
