<?php

/**
 * @file
 * Defines the Order entity and associated features.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_field_widget_form_alter().
 *
 * Changes the label of the purchased_entity field to the label of the target
 * type (e.g. 'Product variation').
 */
function commerce_order_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field_definition = $context['items']->getFieldDefinition();
  $field_name = $field_definition->getName();
  $entity_type = $field_definition->getTargetEntityTypeId();
  $widget_name = $context['widget']->getPluginId();
  if ($field_name == 'purchased_entity' && $entity_type == 'commerce_line_item') {
    if (!empty($element['target_id']['#target_type'])) {
      $target_type = \Drupal::entityManager()->getDefinition($element['target_id']['#target_type']);
      $element['target_id']['#title'] = $target_type->getLabel();
    }
  }
}

/**
 * Adds the default line_items field to an order type.
 *
 * Line items can't be a base field because the Views integration is broken.
 * Instead, it is created as a configurable field for each order type.
 *
 * @param \Drupal\commerce_order\Entity\OrderTypeInterface $order_type
 *   The order type.
 */
function commerce_order_add_line_items_field($order_type) {
  $field_storage = FieldStorageConfig::loadByName('commerce_order', 'line_items');
  $field = FieldConfig::loadByName('commerce_order', $order_type->id(), 'line_items');
  if (empty($field_storage)) {
    $field_storage = FieldStorageConfig::create([
      'field_name' => 'line_items',
      'entity_type' => 'commerce_order',
      'type' => 'entity_reference',
      'cardinality' => FieldStorageConfig::CARDINALITY_UNLIMITED,
      'settings' => [
        'target_type' => 'commerce_line_item',
      ],
      'locked' => TRUE,
      'translatable' => FALSE,
    ]);
    $field_storage->save();
  }
  if (empty($field)) {
    $field = FieldConfig::create([
      'field_storage' => $field_storage,
      'bundle' => $order_type->id(),
      'label' => 'Line items',
      'required' => TRUE,
      'settings' => [
        'handler' => 'default',
        'handler_settings' => [],
      ],
      'translatable' => FALSE,
    ]);
    $field->save();

    // Assign widget settings for the 'default' form mode.
    entity_get_form_display('commerce_order', $order_type->id(), 'default')
      ->setComponent('line_items', [
        'type' => 'inline_entity_form_complex',
        'weight' => 0,
      ])
      ->save();
  }
}
